version: "3.8"
services:
  frontend_convites:
    image: ghcr.io/thinkindigital/casei-link-frontend:latest
    build:
      context: ./frontend
      args:
        - PLASMIC_AUTH_TOKEN=${PLASMIC_AUTH_TOKEN}
    networks:
      - renacesso
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=renacesso"
        - "traefik.http.routers.frontend-convites.rule=Host(`convites.casei.link`)"
        - "traefik.http.routers.frontend-convites.entrypoints=websecure"
        - "traefik.http.routers.frontend-convites.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.frontend-convites.loadbalancer.server.port=3000"

networks:
  renacesso:
    external: true
    name: renacesso