name: Deploy Frontend Convites

on:
  push:
    branches: [ main ] # Dispara a automação quando houver um push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v3

      - name: 2. Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: 3. Construir e Enviar Imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: ./frontend # Aponta para a pasta do frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/casei-link-frontend:latest
          build-args: |
            PLASMIC_AUTH_TOKEN=${{ secrets.PLASMIC_AUTH_TOKEN }}

      - name: 4. Deploy no Servidor via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/casei-link-platform # Navega para a pasta do projeto no servidor (crie-a se necessário)
            echo "${{ secrets.DOCKER_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/casei-link-frontend:latest
            docker stack deploy -c docker-compose.frontend.yml casei-link-frontend --with-registry-auth